-- MySQL Script generated by MySQL Workbench
-- Fri May  1 18:10:57 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sphereds
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sphereds` ;

-- -----------------------------------------------------
-- Schema sphereds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sphereds` DEFAULT CHARACTER SET latin1 ;
USE `sphereds` ;

-- -----------------------------------------------------
-- Table `sphereds`.`job_statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`job_statistics` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `start_time` DATETIME NULL DEFAULT NULL,
  `end_time` DATETIME NULL DEFAULT NULL,
  `params` VARCHAR(255) NULL DEFAULT NULL,
  `result` INT(11) NULL DEFAULT NULL,
  `comments` VARCHAR(255) NULL DEFAULT NULL,
  `retry_job_id` BIGINT(20) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `sphereds`.`sys_configuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`sys_configuration` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `config_name` VARCHAR(100) NULL DEFAULT NULL,
  `config_value` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sphereds`.`account_2fa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`account_2fa` (
  `org_account_id` BIGINT(20) NOT NULL,
  `transport` VARCHAR(10) NOT NULL,
  `provider` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`org_account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `sphereds`.`org_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_account` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `createdby` VARCHAR(45) NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  `updatedby` VARCHAR(45) NULL DEFAULT NULL,
  `components` LONGTEXT NULL DEFAULT NULL,
  `parent_account_id` BIGINT(20) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL,
  `per` CHAR(1) NULL,
  `currency` CHAR(3) NULL,
  `bill_type` CHAR(1) NULL,
  `enable_email_verification` TINYINT NULL,
  `enable_phone_verification` TINYINT NULL,
  `owner_user_id` BIGINT(20) NULL DEFAULT NULL,
  `state` VARCHAR(30) NULL DEFAULT NULL,
  `locked` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sphereds`.`org_account_ip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_account_ip` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `org_account_id` BIGINT(20) NOT NULL,
  `resourceid` VARCHAR(100) NULL,
  `ipaddress` VARCHAR(100) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `aquired_by` VARCHAR(255) NULL DEFAULT NULL,
  `released_by` VARCHAR(255) NULL DEFAULT NULL,
  `aquired_date` DATETIME NULL DEFAULT NULL,
  `released_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_org_account_ip_org_account1_idx` (`org_account_id` ASC),
  CONSTRAINT `fk_org_account_ip_org_account1`
    FOREIGN KEY (`org_account_id`)
    REFERENCES `sphereds`.`org_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sphereds`.`org_account_security_policy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_account_security_policy` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `org_account_id` BIGINT(20) NOT NULL,
  `policy_id` BIGINT(20) NOT NULL,
  `createdby` VARCHAR(45) NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  `updatedby` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `sphereds`.`org_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password_key` VARCHAR(255) NULL DEFAULT NULL,
  `password_expiry_date` DATETIME NULL DEFAULT NULL,
  `password_retry_count` INT(20) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `createdby` VARCHAR(45) NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  `updatedby` VARCHAR(45) NULL DEFAULT NULL,
  `component` LONGTEXT NULL DEFAULT NULL,
  `terms_accepted` TINYINT(1) NULL,
  `email_verification_token` VARCHAR(255) NULL DEFAULT NULL,
  `phone_verification_token` VARCHAR(255) NULL DEFAULT NULL,
  `mobile_phone_number_1` VARCHAR(45) NULL DEFAULT NULL,
  `mobile_country_code_1` VARCHAR(10) NULL DEFAULT NULL,
  `pin` VARCHAR(45) NULL,
  `default_user_account_id` BIGINT(20) NULL DEFAULT NULL,
  `lockout_expiry_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sphereds`.`org_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `org_account_id` BIGINT(20) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL,
  `access_level` TINYINT(1) NULL DEFAULT NULL,
  `type` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
PACK_KEYS = Default;


-- -----------------------------------------------------
-- Table `sphereds`.`org_account_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_account_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `org_user_id` BIGINT(20) NOT NULL,
  `org_account_id` BIGINT(20) NOT NULL,
  `org_role_id` BIGINT(20) NOT NULL,
  `2fa_username` VARCHAR(255) NULL DEFAULT NULL,
  `2fa_state` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_org_user_accounts_org_user_id_idx` (`org_user_id` ASC),
  INDEX `fk_org_user_accounts_org_account_id_idx` (`org_account_id` ASC),
  INDEX `fk_org_user_accounts_org_role_id_idx` (`org_role_id` ASC),
  CONSTRAINT `fk_org_user_accounts_org_user_id`
    FOREIGN KEY (`org_user_id`)
    REFERENCES `sphereds`.`org_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_org_user_accounts_org_account_id`
    FOREIGN KEY (`org_account_id`)
    REFERENCES `sphereds`.`org_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_org_user_accounts_org_role_id`
    FOREIGN KEY (`org_role_id`)
    REFERENCES `sphereds`.`org_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `sphereds`.`org_site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_site` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `provider_id` INT(11) NULL DEFAULT NULL,
  `provider_type` VARCHAR(10) NULL,
  `access_url` VARCHAR(255) NULL DEFAULT NULL,
  `responseformat` VARCHAR(10) NULL DEFAULT NULL,
  `apikey` VARCHAR(255) NULL DEFAULT NULL,
  `secretkey` VARCHAR(255) NULL DEFAULT NULL,
  `resourcepath` VARCHAR(255) NULL DEFAULT NULL,
  `signin_url` VARCHAR(255) NULL DEFAULT NULL,
  `cookie_domain` VARCHAR(255) NULL DEFAULT NULL,
  `site_vmconsole_url` VARCHAR(255) NULL DEFAULT NULL,
  `site_version` VARCHAR(200) NULL,
  `site_zone_id` VARCHAR(200) NULL DEFAULT NULL,
  `site_domain_id` VARCHAR(200) NULL DEFAULT NULL,
  `site_domain_name` VARCHAR(100) NULL DEFAULT NULL,
  `site_account_id` VARCHAR(100) NULL DEFAULT NULL,
  `site_account_name` VARCHAR(100) NULL DEFAULT NULL,
  `site_user_id` VARCHAR(100) NULL DEFAULT NULL,
  `site_user_name` VARCHAR(100) NULL DEFAULT NULL,
  `site_user_password` VARCHAR(100) NULL DEFAULT NULL,
  `site_ip_type` VARCHAR(100) NULL DEFAULT NULL,
  `org_account_owner_id` BIGINT(20) NULL DEFAULT NULL,
  `access_type` VARCHAR(30) NULL DEFAULT NULL,
  `state` VARCHAR(30) NULL DEFAULT NULL,
  `component` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sphereds`.`org_device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_device` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `org_site_id` BIGINT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `accessurl` VARCHAR(255) NULL DEFAULT NULL,
  `accessport` INT(11) NULL DEFAULT NULL,
  `accessid` VARCHAR(45) NULL DEFAULT NULL,
  `secretkey` VARCHAR(100) NULL DEFAULT NULL,
  `component` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_org_device_org_site1_idx` (`org_site_id` ASC),
  CONSTRAINT `fk_org_device_org_site1`
    FOREIGN KEY (`org_site_id`)
    REFERENCES `sphereds`.`org_site` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sphereds`.`org_manage_command`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_manage_command` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `command_name` VARCHAR(45) NULL DEFAULT NULL,
  `command` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sphereds`.`org_device_command`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_device_command` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `org_device_id` BIGINT(20) NOT NULL,
  `org_manage_command_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_org_device_command_org_device1_idx` (`org_device_id` ASC),
  INDEX `fk_org_device_command_org_manage_command1_idx` (`org_manage_command_id` ASC),
  CONSTRAINT `fk_org_device_command_org_device1`
    FOREIGN KEY (`org_device_id`)
    REFERENCES `sphereds`.`org_device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_org_device_command_org_manage_command1`
    FOREIGN KEY (`org_manage_command_id`)
    REFERENCES `sphereds`.`org_manage_command` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sphereds`.`org_module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_module` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `active` TINYINT(1) NULL,
  `site_module` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `sphereds`.`org_site_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_site_account` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `org_account_id` BIGINT(20) NOT NULL,
  `org_site_id` INT(11) NOT NULL,
  `site_domain_id` VARCHAR(255) NULL DEFAULT NULL,
  `site_domain_name` VARCHAR(255) NULL DEFAULT NULL,
  `site_account_id` VARCHAR(255) NULL DEFAULT NULL,
  `site_account_name` VARCHAR(255) NULL DEFAULT NULL,
  `site_user_id` VARCHAR(255) NULL DEFAULT NULL,
  `site_user_name` VARCHAR(255) NULL DEFAULT NULL,
  `site_user_password` VARCHAR(255) NULL DEFAULT NULL,
  `apikey` VARCHAR(255) NULL DEFAULT NULL,
  `secretkey` VARCHAR(255) NULL DEFAULT NULL,
  `parent_site_domain_id` VARCHAR(255) NULL DEFAULT NULL,
  `state` VARCHAR(30) NULL DEFAULT NULL,
  `initialized` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_org_account_site_org_account1` (`org_account_id` ASC),
  CONSTRAINT `fk_org_account_site_org_account1`
    FOREIGN KEY (`org_account_id`)
    REFERENCES `sphereds`.`org_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `sphereds`.`org_site_ip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_site_ip` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `org_site_id` INT(11) NOT NULL,
  `siteresourceid` VARCHAR(100) NULL,
  `ipaddress` VARCHAR(100) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `aquired_by` BIGINT(20) NULL DEFAULT NULL,
  `released_by` BIGINT(20) NULL DEFAULT NULL,
  `aquired_date` DATETIME NULL DEFAULT NULL,
  `released_date` DATETIME NULL DEFAULT NULL,
  `reservation_id` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sphereds`.`org_role_module_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_role_module_permission` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `org_role_id` BIGINT NOT NULL,
  `org_module_id` BIGINT NOT NULL,
  `permission` INT NOT NULL,
  PRIMARY KEY (`id`, `org_role_id`, `org_module_id`),
  INDEX `fk_org_role_module_permission_org_module1_idx` (`org_module_id` ASC),
  INDEX `fk_org_role_module_permission_id_org_role_id_idx` (`org_role_id` ASC),
  CONSTRAINT `fk_org_role_module_permission_org_role_id`
    FOREIGN KEY (`org_role_id`)
    REFERENCES `sphereds`.`org_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_org_role_module_permission_org_module_id`
    FOREIGN KEY (`org_module_id`)
    REFERENCES `sphereds`.`org_module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `sphereds`.`org_user_password_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_user_password_history` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `org_user_id` BIGINT(20) NOT NULL,
  `previous_password` VARCHAR(255) NOT NULL,
  `password_change_date` DATETIME NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `createdby` VARCHAR(45) NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  `previous_password_key` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sphereds`.`resource_whitelist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`resource_whitelist` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `resource_id` VARCHAR(100) NULL DEFAULT NULL,
  `account_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `sphereds`.`security_policy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`security_policy` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `policy_cd` VARCHAR(50) NOT NULL,
  `policy_description` VARCHAR(100) NOT NULL,
  `policy_type` VARCHAR(100) NOT NULL,
  `noofcharsrule` INT(5) NULL DEFAULT NULL,
  `minlength` INT(5) NULL DEFAULT NULL,
  `maxlength` INT(5) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `createdby` VARCHAR(45) NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  `updatedby` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sphereds`.`type_theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`type_theme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `org_account_id` INT(11) NULL DEFAULT NULL,
  `url` VARCHAR(45) NULL COMMENT '  ',
  `logo` BLOB NULL COMMENT ' ',
  `component` TEXT NULL,
  `uuid` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sphereds`.`org_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_resource` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `siteid` INT NULL,
  `accountid` BIGINT NULL,
  `siteresourceid` VARCHAR(100) NULL,
  `resourcetype` VARCHAR(45) NULL,
  `cru` DOUBLE NULL DEFAULT 0,
  `created` DATETIME NULL,
  `state` VARCHAR(10) NULL,
  `name` VARCHAR(250) NULL,
  `resourceid` VARCHAR(100) NULL,
  `component` TEXT NULL DEFAULT NULL,
  `destroyed` DATETIME NULL DEFAULT NULL,
  `access_level` TINYINT(1) NULL DEFAULT NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  INDEX `RESOURCEID` (`resourceid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sphereds`.`org_sms_gateway`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_sms_gateway` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '	',
  `org_account_id` BIGINT(20) NOT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `api_key` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `sphereds`.`org_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_token` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `org_user_account_id` BIGINT(20) NOT NULL,
  `token_id` TEXT NOT NULL,
  `expire` DATETIME NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sphereds`.`org_serialize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_serialize` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reference_id` MEDIUMTEXT NULL COMMENT ' ',
  `serialize_obj` LONGBLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sphereds`.`org_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_event` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `state` INT(11) NULL,
  `accountid` BIGINT(20) NULL,
  `userid` BIGINT(20) NOT NULL,
  `createdby` BIGINT(20) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `uuid` VARCHAR(255) NOT NULL,
  `itemid` VARCHAR(255) NULL,
  `component` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sphereds`.`org_paypal_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_paypal_account` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `org_account_id` BIGINT(20) NULL,
  `active` TINYINT(1) NULL COMMENT '	',
  `component` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sphereds`.`org_paypal_credit_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_paypal_credit_card` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `paypal_credit_card_id` VARCHAR(255) NULL,
  `active` TINYINT(1) NULL,
  `component` LONGTEXT NULL,
  `org_account_id` BIGINT(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sphereds`.`org_provider_site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_provider_site` (
  `id` INT NOT NULL,
  `service` VARCHAR(45) NULL COMMENT '	',
  `name` VARCHAR(255) NULL,
  `provider` VARCHAR(45) NULL COMMENT '	',
  `component` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sphereds`.`org_user_verification_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_user_verification_status` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `org_user_id` BIGINT(20) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `org_user_id_fk_idx` (`org_user_id` ASC),
  CONSTRAINT `org_user_id_fk`
    FOREIGN KEY (`org_user_id`)
    REFERENCES `sphereds`.`org_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `sphereds`.`pricing_period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`pricing_period` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `org_account_id` BIGINT(20) NULL DEFAULT NULL,
  `effective_date` DATETIME NULL DEFAULT NULL,
  `expiry_date` DATETIME NULL DEFAULT NULL,
  `updated_by` BIGINT(20) NULL DEFAULT NULL,
  `active` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `sphereds`.`pricing_meter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`pricing_meter` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `pricing_period_id` BIGINT(20) NOT NULL,
  `org_site_id` BIGINT(20) NOT NULL,
  `variable_price` DOUBLE NOT NULL DEFAULT '0',
  `resource_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_org_domain_meter_history_billing_term1_idx` (`pricing_period_id` ASC),
  CONSTRAINT `fk_pricing_meter_pricing_period`
    FOREIGN KEY (`pricing_period_id`)
    REFERENCES `sphereds`.`pricing_period` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `sphereds`.`raw_usage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`raw_usage` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT NULL,
  `resource_id` VARCHAR(255) NULL DEFAULT NULL,
  `charge_type` TINYINT NULL,
  `amount` DOUBLE NULL,
  `duration` DOUBLE NULL DEFAULT NULL,
  `period_start` DATETIME NULL DEFAULT NULL,
  `period_end` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sphereds`.`billing_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`billing_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT NULL,
  `resource_id` VARCHAR(255) NULL,
  `category` TINYINT NULL,
  `charge_type` TINYINT NULL,
  `bill_day` DATETIME NULL,
  `units` DOUBLE NULL,
  `cost` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sphereds`.`org_resource_cost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_resource_cost` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `org_account_id` BIGINT NULL,
  `resource_id` VARCHAR(255) NULL,
  `current` TINYINT(1) NULL,
  `variable_cost` DOUBLE NULL,
  `effective_date` DATETIME NULL,
  `expiry_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sphereds`.`term`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`term` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `org_account_id` BIGINT(20) NOT NULL,
  `details` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sphereds`.`org_site_module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_site_module` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `org_module_id` BIGINT NOT NULL,
  `org_site_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_org_site_module_org_module_id_idx` (`org_module_id` ASC),
  INDEX `fk_org_site_module_org_site_id_idx` (`org_site_id` ASC),
  CONSTRAINT `fk_org_site_module_org_module_id`
    FOREIGN KEY (`org_module_id`)
    REFERENCES `sphereds`.`org_module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_org_site_module_org_site_id`
    FOREIGN KEY (`org_site_id`)
    REFERENCES `sphereds`.`org_site` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sphereds`.`org_account_invite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sphereds`.`org_account_invite` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `org_account_id` BIGINT NOT NULL,
  `org_role_id` BIGINT NOT NULL,
  `email` VARCHAR(255) NULL,
  `hash` VARCHAR(400) NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `org_account_invite_org_account_id_fk_idx` (`org_account_id` ASC),
  INDEX `org_account_invite_org_role_id_fk_idx` (`org_role_id` ASC),
  CONSTRAINT `org_account_invite_org_account_id_fk`
    FOREIGN KEY (`org_account_id`)
    REFERENCES `sphereds`.`org_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `org_account_invite_org_role_id_fk`
    FOREIGN KEY (`org_role_id`)
    REFERENCES `sphereds`.`org_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
